# Sign up
POST http://0.0.0.0:8403/api/v1/auth/signup
Content-Type: application/json
Content-Length: 64
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip

{"email":"example@ccc.cc", "password":"examplePassword"}

###
# Sign in with email and password
POST http://0.0.0.0:8403/api/v1/auth/token?grantType=password
Content-Type: application/json
Content-Length: 64
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip

{"email":"example@ccc.cc", "password":"examplePassword"}

###
# Sign in with email and password
POST http://0.0.0.0:8403/api/v1/auth/token?grantType=refreshToken
Content-Type: application/json
Content-Length: 64
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip

{"refreshToken":"9hBnXyCbQttx2oM3lrIPgry0Zh3BaS7scnC0dpoB9SmBhFhV4mjko6YWtFClKyI8"}

###
# Sign out
POST http://0.0.0.0:8403/api/v1/auth/signout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VyIiwiZXhwIjoxNjg3NzQ2NDczLCJpYXQiOjE2ODc3NDI4NzMsImlzcyI6ImF1dGhjYXJlLXYxIiwic3ViIjoiNjAxYWVjZGItZDdiNy00NjhlLTgwN2EtYTZiYTFiZTFmMTM0Iiwic2lkIjoiZWUxMjJhOWYtY2I0ZC00M2RiLWExYmMtNzE1NzA2ZTJhZWQ4In0.uqoFkvNK6lELd7u_4qNBZ6NkNRacmEZxZLPYCGdElyc
Content-Length: 0
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip