# Sign up
POST http://0.0.0.0:8403/api/v1/auth/signup
Content-Type: application/json
Content-Length: 64
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip

{"email":"example@email.com", "password":"examplePassword"}

###
# Sign in with email and password
POST http://0.0.0.0:8403/api/v1/auth/token?grantType=password
Content-Type: application/json
Content-Length: 64
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip

{"email":"example@ccc.cc", "password":"examplePassword"}

###
# Sign in with email and password
POST http://0.0.0.0:8403/api/v1/auth/token?grantType=refreshToken
Content-Type: application/json
Content-Length: 64
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip

{"refreshToken":"9hBnXyCbQttx2oM3lrIPgry0Zh3BaS7scnC0dpoB9SmBhFhV4mjko6YWtFClKyI8"}

###
# Sign out
POST http://0.0.0.0:8403/api/v1/auth/signout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VyIiwiZXhwIjoxNjg3NzQ2NDczLCJpYXQiOjE2ODc3NDI4NzMsImlzcyI6ImF1dGhjYXJlLXYxIiwic3ViIjoiNjAxYWVjZGItZDdiNy00NjhlLTgwN2EtYTZiYTFiZTFmMTM0Iiwic2lkIjoiZWUxMjJhOWYtY2I0ZC00M2RiLWExYmMtNzE1NzA2ZTJhZWQ4In0.uqoFkvNK6lELd7u_4qNBZ6NkNRacmEZxZLPYCGdElyc
Content-Length: 0
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip

###
# Get access token info
GET http://0.0.0.0:8403/api/v1/auth/token?accessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VyIiwiZXhwIjoxNjg4NTIwNjU2LCJpYXQiOjE2ODg1MTcwNTYsImlzcyI6ImF1dGhjYXJlLXYxIiwic3ViIjoiMGNmNmU4YzItYjFjMy00YmY5LWFkMGMtZGVlNTc5MTIwMzJiIiwic2lkIjoiZjgxM2Q5YWMtODRkYy00ZTRhLWI4YmEtNDQ2NTBkMTZiYjY1In0.VMDiUDG4moMNCdQuE3fo_f-uMEWgfenHRmP9GtlNS24
Content-Type: application/json
Content-Length: 64
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip

###
# Get access token info
GET http://0.0.0.0:8080/api/v1/domain_name/domain
Content-Type: application/json
Content-Length: 64
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip

{"name":"google.com", "expirationDate": "Wed, 05 Jul 2023 00:35:33 GMT"}

###
# Siwa
POST http://0.0.0.0:8403/api/v1/auth/token?grantType=idToken
Content-Type: application/json
Content-Length: 64
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "client": "app.namecare.ios",
  "token": "eyJraWQiOiJXNldjT0tCIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiYXBwLm5hbWVjYXJlLmlvcyIsImV4cCI6MTY4OTYyOTk3MSwiaWF0IjoxNjg5NTQzNTcxLCJzdWIiOiIwMDEwOTEuMjJjMGNhNTk0ZDQyNDNjNThlZGYzNTUzNTQwMzgwYjUuMjA0NSIsImNfaGFzaCI6Ik8xeUVwY1dQbExDdXU4NnFrbGtvRmciLCJlbWFpbCI6ImVjcjlwYmhpbXVAcHJpdmF0ZXJlbGF5LmFwcGxlaWQuY29tIiwiZW1haWxfdmVyaWZpZWQiOiJ0cnVlIiwiaXNfcHJpdmF0ZV9lbWFpbCI6InRydWUiLCJhdXRoX3RpbWUiOjE2ODk1NDM1NzEsIm5vbmNlX3N1cHBvcnRlZCI6dHJ1ZX0.WvnvubpILn6cGNeEdh_Jqy18Q9h_OHz0pRnva6ZtAt6POnj_QqTQt1zola8fB5L1FMgbytGEnFxPW9sLuSYXGMEDtAl7-Wex3BSIzTOJBQqpz_HL3zVTInLAlNU36cBPUN0hhhe027T5__Hx1Ptcjwpj9RKpiPGoHRPB_MrhULL2djS_seFcpZaG01-Y5sPiQKpJVVjDECxnvO1OXDtL-FWQLUALAIFLFaIdYwrX0kncmcusHzZEa0DzGG9rfJ-J0Y_jFKmaUkHLpeWuxKV_0H_DQn1zDOy8fuB9MVFIo9FRUjuCxPXXmttT3WyeqCH2_iUM5jmEUkge78V6g68qSw",
  "provider": "apple",
  "issuer": "https://appleid.apple.com"
}